### PR TITLE
to keep the intended original error in the event the close_wrapper is ok

### PR DESCRIPTION
**Pull request by diclophis**
I think this is intended result?

### CODE REVIEW

**Comment by diclophis** [comment]
@Asmod4n any luck getting a chance to scope out this change?

**Comment by Asmod4n** [comment]
@diclophis Strange, I didn’t get a email about your PR. But could you send a PR upstream?

**Comment by diclophis** [comment]
@Asmod4n I am not sure what you mean?

**Comment by Asmod4n** [comment]
@diclophis please Open your PR at https://github.com/tatsuhiro-t/wslay

**Pull request closed without merging**
